spring:
    application:
        name: "store-service"
    threads:
        virtual:
            enabled: true

store-service:
    store:
        dataset-location: "classpath:stores.json"
        timezone: "Europe/Amsterdam"

logging:
    level:
        root: info
        be.lennertsoffers: debug